command -nargs=* -range ChatGPT call chatgpt#raw(<q-args>)
command -nargs=* -range ChatGPTExplain call chatgpt#explain(<q-args>)
command -nargs=* -range ChatGPTRewrite call chatgpt#rewrite(<q-args>)
command -nargs=* -range ChatGPTFix call chatgpt#fix(<q-args>)
command -nargs=* -range ChatGPTCodeReviewPlease call chatgpt#review(<q-args>)
command -nargs=0 ChatGPTCodeReviewWholeFilePlease call chatgpt#code_review_please()
command -nargs=* ChatGPTSetRole call chatgpt#set_role(<q-args>)
